name: Rust CI

# Controls when the action will run.
on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on Rust ${{ matrix.rust-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Build and test
        run: |
          cargo build --verbose --release
          cargo test --verbose --release

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Login to crates.io
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo login --token $CRATES_IO_TOKEN

      - name: Package and publish
        run: |
          cargo package --allow-dirty
          cargo publish --token $CRATES_IO_TOKEN
